# 3주차 과제 2번째

#### 통계학과 201618968 김종원

### Import 

In [1]:
import torch 
import numpy as np 

`-` model: $y_i= w_0+w_1 x_{i1}+w_2 x_{i2} +\epsilon_i = 2.5 + 4x_{1i} -2x_{2i}+\epsilon_i, \quad i=1,2,\dots,n$ 

In [2]:
torch.manual_seed(43052)
n=100
ones= torch.ones(n)
x1,_ = torch.randn(n).sort()
x2,_ = torch.randn(n).sort()
X = torch.vstack([ones,x1,x2]).T
W = torch.tensor([2.5,4,-2])
ϵ = torch.randn(n)*0.5
y = X@W + ϵ
ytrue = X@W

`-` torch.nn.Linear() 를 이용하여 $\bf{\hat{W}}=\begin{bmatrix}1 \\ 1 \\ 1 \end{bmatrix}$ 에 대한 $\hat{y}$를 구하라. 

In [3]:
net = torch.nn.Linear(in_features=3, out_features=1, bias=False)

In [4]:
net.weight.data

tensor([[-0.5259, -0.5518,  0.1700]])

In [5]:
net.weight.data=torch.tensor( [ [1.0, 1.0, 1.0] ] )
net.weight.data

tensor([[1., 1., 1.]])

In [6]:
yhat=net(X)
yhat

tensor([[-3.8542],
        [-3.6654],
        [-3.2244],
        [-2.6540],
        [-2.3949],
        [-2.2877],
        [-2.1205],
        [-2.1110],
        [-1.8446],
        [-1.7484],
        [-1.6015],
        [-1.4912],
        [-1.4857],
        [-1.4330],
        [-1.2724],
        [-1.2179],
        [-1.1147],
        [-0.9953],
        [-0.9047],
        [-0.8572],
        [-0.7928],
        [-0.6712],
        [-0.5655],
        [-0.5293],
        [-0.4903],
        [-0.4266],
        [-0.3574],
        [-0.2255],
        [-0.1800],
        [-0.1702],
        [-0.0791],
        [-0.0280],
        [ 0.0160],
        [ 0.1480],
        [ 0.2441],
        [ 0.3293],
        [ 0.3503],
        [ 0.3997],
        [ 0.4105],
        [ 0.4984],
        [ 0.5157],
        [ 0.5393],
        [ 0.5820],
        [ 0.6235],
        [ 0.6382],
        [ 0.6687],
        [ 0.7057],
        [ 0.7568],
        [ 0.7995],
        [ 0.9063],
        [ 0.9989],
        [ 1.0058],
        [ 1.