# 11주차 과제 1번째

#### 통계학과 201618968 김종원

#### 환경 : colab

### import 

In [1]:
import torch

### data 

In [3]:
ones= torch.ones(5)
x = torch.tensor([11.0,12.0,13.0,14.0,15.0])
X = torch.vstack([ones,x]).T
y = torch.tensor([17.7,18.5,21.2,23.6,24.2])

W = torch.tensor([3.0,3.0]) 

u = X@W 
v = y-u 

### 실행

In [4]:
v

tensor([-18.3000, -20.5000, -20.8000, -21.4000, -23.8000])

In [5]:
_v= torch.tensor([-18.3000, -20.5000, -20.8000, -21.4000, -23.8000],requires_grad=True)

In [6]:
_loss = _v.T @ _v 

In [7]:
_loss.backward() 

In [11]:
_v.grad.data, v

(tensor([-36.6000, -41.0000, -41.6000, -42.8000, -47.6000]),
 tensor([-18.3000, -20.5000, -20.8000, -21.4000, -23.8000]))